# Site settings
title: Chris Tweedie
email: 
description: > # this means to ignore newlines until "baseurl:"
  Chris's personal blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cltweedie.github.io" # the base hostname & protocol for your site
twitter_username: ctweedz
github_username: cltweedie

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
